### PR TITLE
Add events to Marker

### PR DESCRIPTION
**Pull request by JaWeilBaum**
I've just added 2 events to the marker.

- `move` - while the marker is dragged, this event fires. It also updates the internal `latLng` values
- `moveend` - this event is fired when dragging has ended. The event sent also contains its `sender`which in this case would be the marker it self. With this, the new positon can be read from this event.

### CODE REVIEW

**Comment by JaWeilBaum** [comment]
@samhattangady @shikharp16

**Comment by JaWeilBaum** [comment]
I assume this project will not further be maintained? @samhattangady @shikharp16

**Comment by samhattangady** [comment]
@JaWeilBaum Hey. I am sorry for the delayed response. Unfortunately, we have stopped using pyqtlet for our desktop apps, and do not plan to support this module anymore.

**Comment by JaWeilBaum** [comment]
Alright, do you use any other library/framework for maps (with pyqt5) or do you just don't need the map functionality any more?

**Comment by samhattangady** [comment]
We have been using web based solutions, so we just use leaflet directly now.

**Comment by samhattangady** [comment]
@JaWeilBaum I have updated the readme to point users towards your fork of the project.

**Pull request closed without merging**
